Failure # 1 (occurred at 2024-12-05_01-29-48)
[36mray::ImplicitFunc.train()[39m (pid=2538692, ip=141.142.254.145, actor_id=9698df2d7d7826cc36e5efb201000000, repr=train_tune_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u/mbanisharifdehkordi/test_env_11/lib/python3.11/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/u/mbanisharifdehkordi/test_env_11/lib/python3.11/site-packages/ray/air/_internal/util.py", line 107, in run
    self._ret = self._target(*self._args, **self._kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u/mbanisharifdehkordi/test_env_11/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u/mbanisharifdehkordi/test_env_11/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 250, in _trainable_func
    output = fn()
             ^^^^
  File "/u/mbanisharifdehkordi/Github/Cell Counting/ray_tune.py", line 115, in train_tune_model
    tune.report(val_loss=val_loss / len(val_loader))
    ^^^^^^^^^^^
AttributeError: module 'ray.tune' has no attribute 'report'
